

get-data:
	wget -N -P downloaded-data/2016-17 http://www.dpi.state.nc.us/docs/fbs/resources/data/2016-17/expend-report.xls
	wget -N -P downloaded-data/2015-16 http://www.dpi.state.nc.us/docs/fbs/resources/data/2015-16/expend-report.xls
	wget -N -P downloaded-data/2014-15 http://www.dpi.state.nc.us/docs/fbs/resources/data/expendrpt14-15.xls
	wget -N -P downloaded-data/2013-14 http://www.dpi.state.nc.us/docs/fbs/resources/data/expendrpt13-14.xls
