

get-data:
	wget -N -P downloaded-data/2016-17 http://www.dpi.state.nc.us/docs/fbs/resources/data/2016-17/expend-report.xls
	wget -N -P downloaded-data/2015-16 http://www.dpi.state.nc.us/docs/fbs/resources/data/2015-16/expend-report.xls
	wget -N -P downloaded-data/2014-15 http://www.dpi.state.nc.us/docs/fbs/resources/data/expendrpt14-15.xls
	wget -N -P downloaded-data/2013-14 http://www.dpi.state.nc.us/docs/fbs/resources/data/expendrpt13-14.xls

get-ccd-data:
	wget -N -P downloaded-data https://nces.ed.gov/ccd/data/zip/sdf14_1a_flat.zip
	wget -N -P downloaded-data https://nces.ed.gov/ccd/data/txt/sdf14_1a_layout.txt
	wget -N -P downloaded-data https://nces.ed.gov/ccd/data/zip/sdf13_1a.zip
	wget -N -P downloaded-data https://nces.ed.gov/ccd/data/txt/sdf13_1a_layout.txt 
	wget -N -P downloaded-data https://nces.ed.gov/ccd/data/zip/sdf121a.zip
	wget -N -P downloaded-data https://nces.ed.gov/ccd/data/txt/sdf121alayout.txt
	wget -N -P downloaded-data https://nces.ed.gov/ccd/data/zip/sdf11_1a_txt.zip
	wget -N -P downloaded-data https://nces.ed.gov/ccd/data/txt/sdf11_1a_layout.txt
	wget -N -P downloaded-data https://nces.ed.gov/ccd/data/zip/SDF101a_txt.zip
	wget -N -P downloaded-data https://nces.ed.gov/ccd/data/txt/sdf101alayout.txt
	wget -N -P downloaded-data https://nces.ed.gov/ccd/data/zip/SDF091a_txt.zip
	wget -N -P downloaded-data https://nces.ed.gov/ccd/data/txt/sdf091alayout.txt
	wget -N -P downloaded-data https://nces.ed.gov/ccd/data/zip/sdf081a_txt.zip
	wget -N -P downloaded-data https://nces.ed.gov/ccd/data/txt/sdf081alayout.txt
	wget -N -P downloaded-data https://nces.ed.gov/ccd/data/zip/sdf071a.txt.zip
	wget -N -P downloaded-data https://nces.ed.gov/ccd/data/txt/sdf071alayout.txt
	wget -N -P downloaded-data https://nces.ed.gov/ccd/data/zip/sdf061a.txt.zip
	wget -N -P downloaded-data https://nces.ed.gov/ccd/data/txt/sdf061alay.txt
	wget -N -P downloaded-data https://nces.ed.gov/ccd/data/zip/sdf051c.txt.zip
	wget -N -P downloaded-data https://nces.ed.gov/ccd/data/txt/sdf051clay.txt
	wget -N -P downloaded-data https://nces.ed.gov/ccd/data/zip/sdf041b.txt.zip
	wget -N -P downloaded-data https://nces.ed.gov/ccd/data/txt/sdf041blay.txt
	wget -N -P downloaded-data https://nces.ed.gov/ccd/data/zip/sdf031b.txt.zip
	wget -N -P downloaded-data https://nces.ed.gov/ccd/data/txt/sdf031blay.txt
	# more data on the webiste back to 1990 
	# https://nces.ed.gov/ccd/f33agency.asp
